language: node_js

node_js:
  - stable

script:
  - npm run-script test-travis

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_script:
  - npm install coveralls && cat ./coverage/lcov.info | ./node_modules/.bin/coveralls

notifications:
  email: false