enum ActionTypes {
  ARENA_SWITCH_ANIMATION_NEXTPHRASE = "ARENA_SWITCH_ANIMATION_NEXTPHRASE",
  ARENA_SWITCH_ANIMATION_PLAY_NEXT = "ARENA_SWITCH_ANIMATION_PLAY_NEXT",
  ARENA_SWITCH_ANIMATION_PLAY_ADD = "ARENA_SWITCH_ANIMATION_PLAY_ADD",
  ARENA_SWITCH_ANIMATION_PLAY_REMOVE = "ARENA_SWITCH_ANIMATION_NEXTPHRASE",
  ARENA_SWITCH_ANIMATION_PLAY_UPDATE = "ARENA_SWITCH_ANIMATION_PLAY_UPDATE"
}

export default ActionTypes;
